### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by jasonbahl** [djfarly/gatsby-plugin-graphql-preview#8]
Hey! 

This idea looks great. I haven’t had a chance to try it, but wanted to ask a few questions. 

If this is using the `gatsby-source-graphql` do previews only work while in dev mode? So the user would have to run `gatsby develop` to see the live previews? Or does it somehow unstitch the Schema to allow for live previewing even when Gatsby is not in develop mode? I.e. queries are executed against the external GraphQL source from the exported static site?

I’ve been trying to think through the best way to do previews for WordPress + Gatsby sites using WPGraphQL, and I feel like the only way is to _not_ use `gatsby-source-graphql` because the stitching seems to screw things up a bit. 

Maybe I need to play with it more. This looks sweet though! Definitely keeping an eye on it.

**Comment by djfarly** [comment]
Hej Jason,

yea, unstitching the Schema maybe describes what it does. In code I call it isolating the query because it does not care about the Schema much.

It does the following:
- find the part of the query corresponding to the fieldName stated in your source-graphql settings.
- make that the new root, remove all other root fields
- rename all types by stripping the typeName prefix (also from the source-graphql settings)
- remove all fragments that are not used anymore

Later when actually making the query on the client, it transform the result - adding the typeName prefix to all __typenames (Code kinda often depends on that).

Also it merges it back into the statically queried data from gatsby.

Thus yes, it also works when build - in fact this was the main focus since we wanted something that can show editors their changes without waiting for some pipeline to finish.

As long as you’re using source graphql to connect to Wordpress it should just work ™️.

Looking forward to hear if this can solve your problem :)

**Comment by jasonbahl** [comment]
Ya. This looks sweet. Sounds like exactly what I need. I’ll check it out shortly. Thanks!!
